# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('intervencion_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_intervencion', models.PositiveIntegerField(verbose_name='Número de intervención')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico técnico')),
                ('procedimientos', models.TextField(verbose_name='Procedimientos aplicados')),
                ('materiales_utilizados', models.TextField(verbose_name='Materiales utilizados')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='ficha_tecnica.fichatecnica', verbose_name='Ficha técnica')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'db_table': 'intervencion',
                'ordering': ['ficha', 'n_intervencion'],
            },
        ),
    ]
