# Generated by Django 5.0.3 on 2025-12-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
