# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
        ('manejo_plagas', '0001_initial'),
        ('tipo_plaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPlaga',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('conteo_larvas', models.IntegerField()),
                ('conteo_esqueletos', models.IntegerField()),
                ('conteo_incisiones', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_tecnica.fichatecnica')),
                ('manejo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_plagas.manejoplagas')),
                ('tipologia_plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_plaga.tipoplaga')),
            ],
            options={
                'verbose_name': 'Registro de Plaga',
                'verbose_name_plural': 'Registros de Plagas',
            },
        ),
    ]
