# Generated by Django 5.0.3 on 2025-12-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_plaga', '0002_registroplaga_usuario_registro'),
        ('tipo_plaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplaga',
            name='conteo_tapones',
            field=models.IntegerField(blank=True, default=0, help_text='Orificios sellados por el insecto (indicador de actividad pasada)', null=True, verbose_name='Conteo de tapones'),
        ),
        migrations.AlterField(
            model_name='registroplaga',
            name='conteo_esqueletos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroplaga',
            name='conteo_incisiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroplaga',
            name='conteo_larvas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroplaga',
            name='tipologia_plaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_plaga.tipoplaga', verbose_name='Tipo de plaga'),
        ),
    ]
