# Generated by Django 5.2.6 on 2025-11-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de material')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
                'db_table': 'catalogo_material_tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'catalogo_organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('sala', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sala')),
                ('caja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'catalogo_ubicacion',
                'ordering': ['sector', 'sala', 'caja'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía / Descripción')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'catalogo_autores',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.autor')),
            ],
            options={
                'verbose_name': 'Colaboración',
                'verbose_name_plural': 'Colaboraciones',
                'db_table': 'catalogo_colaboracion',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_obra', models.CharField(choices=[('L', 'Libro'), ('A', 'Artículo'), ('E', 'Ensayo'), ('O', 'Otro')], default='L', max_length=1, verbose_name='Tipo de Obra')),
                ('fecha_publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Publicación')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('autores', models.ManyToManyField(related_name='obras_participadas', through='catalogos.Colaboracion', to='catalogos.autor', verbose_name='Autores y Colaboradores')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'catalogo_obras',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Foto')),
                ('url_video', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Video')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fk_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='catalogos.obra', verbose_name='Obra asociada')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedias',
                'db_table': 'catalogo_multimedia',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.obra'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_prestamo', models.CharField(max_length=50, unique=True)),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('direccion_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('seguro_soliditado', models.BooleanField(default=False)),
                ('costo_traslado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin_prevista', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_estimada', models.DateField(blank=True, null=True)),
                ('requisitos_especiales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('fk_item', models.ForeignKey(db_column='fk_item_id', on_delete=django.db.models.deletion.CASCADE, to='catalogos.obra', verbose_name='Obra / Item')),
                ('fk_organizacion_destino', models.ForeignKey(db_column='fk_organizacion_destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_destino', to='catalogos.organizacion')),
                ('fk_organizacion_origen', models.ForeignKey(db_column='fk_organizacion_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_origen', to='catalogos.organizacion')),
                ('fk_responsable_prestamo', models.ForeignKey(db_column='fk_responsable_prestamo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del préstamo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'catalogo_prestamos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='colaboracion',
            unique_together={('obra', 'autor')},
        ),
    ]
