# Generated by Django 5.0.3 on 2025-12-25 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0002_initial'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_prestamo', models.CharField(max_length=50)),
                ('direccion_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('seguro_solicitado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_traslado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_prevista', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('requisitos_especiales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='ficha_tecnica.fichatecnica')),
                ('institucion_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_destino', to='institucion.institucion')),
                ('institucion_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_origen', to='institucion.institucion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_responsable', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_cargados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
