# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_EVALUACION', 'En evaluación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PREPARACION', 'En preparación'), ('EN_TRANSITO_IDA', 'En tránsito (ida)'), ('EN_DESTINO', 'En destino'), ('EN_TRANSITO_VUELTA', 'En tránsito (vuelta)'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=50, verbose_name='Estado del préstamo'),
        ),
    ]
