# Generated by Django 5.2.6 on 2025-11-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía / Descripción')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_obra', models.CharField(choices=[('L', 'Libro'), ('A', 'Artículo'), ('E', 'Ensayo'), ('O', 'Pintura'), ('S', 'Escultura'), ('F', 'Fotografía'), ('M', 'Otro Medio')], default='L', max_length=1, verbose_name='Tipo de Obra')),
                ('fecha_publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Publicación')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='catalogo_autores.autor')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['titulo'],
            },
        ),
    ]
