# Generated by Django 5.2.6 on 2025-11-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obra',
            table='catalogo_obras',
        ),
    ]
