# Generated by Django 5.2.6 on 2025-11-12 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_autores', '0002_alter_obra_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='autor',
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('L', 'Libro'), ('A', 'Artículo'), ('E', 'Ensayo'), ('O', 'Otro')], default='L', max_length=1, verbose_name='Tipo de Obra'),
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_autores.autor')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_autores.obra')),
            ],
            options={
                'verbose_name': 'Colaboración',
                'verbose_name_plural': 'Colaboraciones',
                'db_table': 'colaboraciones',
                'unique_together': {('obra', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='autores',
            field=models.ManyToManyField(related_name='obras_participadas', through='catalogo_autores.Colaboracion', to='catalogo_autores.autor', verbose_name='Autores y Colaboradores'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_estimada', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_prestamos', to='catalogo_autores.obra', verbose_name='Obra Prestada')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamos',
            },
        ),
    ]
