# Generated by Django 5.2.6 on 2025-11-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_autores', '0003_remove_obra_autor_alter_obra_tipo_obra_colaboracion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autores',
        ),
    ]
