# Generated by Django 5.2.6 on 2025-11-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_autores', '0004_alter_autor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='catalogo_autores',
        ),
    ]
