# Generated by Django 5.0.3 on 2025-11-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0003_alter_fichatecnica_fk_estado'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateField(verbose_name='Fecha de la donación')),
                ('condicion_legal', models.TextField(verbose_name='Condición legal')),
                ('valuacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valuación estimada')),
                ('documento_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='documentos_donacion/', verbose_name='Documento PDF')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='ficha_tecnica.fichatecnica', verbose_name='Ficha técnica')),
                ('institucion_donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to='institucion.institucion', verbose_name='Institución donante')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable institucional')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
    ]
