# Generated by Django 5.0.3 on 2025-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateField(verbose_name='Fecha de la donación')),
                ('condicion_legal', models.TextField(verbose_name='Condición legal')),
                ('valuacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valuación estimada')),
                ('documento_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='documentos_donacion/', verbose_name='Documento PDF')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
    ]
