# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donacion', '0001_initial'),
        ('ficha_tecnica', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='ficha_tecnica.fichatecnica', verbose_name='Ficha técnica'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='institucion_donante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to='institucion.institucion', verbose_name='Institución donante'),
        ),
    ]
