# Generated by Django 5.0.3 on 2025-12-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='institucion_donante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_realizadas', to='institucion.institucion', verbose_name='Institución donante'),
        ),
    ]
