# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0004_alter_donacion_institucion_donante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='condicion_legal',
            field=models.CharField(choices=[('PLENA_PROPIEDAD', 'Plena propiedad'), ('COMODATO', 'Comodato'), ('DEPOSITO', 'Depósito'), ('LEGADO', 'Legado testamentario'), ('CESION_TEMPORAL', 'Cesión temporal'), ('USUFRUCTO', 'Usufructo'), ('EN_TRAMITE', 'En trámite'), ('OTRO', 'Otro')], default='PLENA_PROPIEDAD', max_length=50, verbose_name='Condición legal'),
        ),
    ]
