# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='tipo_institucion',
            field=models.CharField(choices=[('MUSEO', 'Museo'), ('UNIVERSIDAD', 'Universidad'), ('FUNDACION', 'Fundación'), ('GALERIA', 'Galería'), ('CENTRO_CULTURAL', 'Centro cultural'), ('BIBLIOTECA', 'Biblioteca'), ('ARCHIVO', 'Archivo'), ('GOBIERNO', 'Institución gubernamental'), ('PRIVADO', 'Colección privada'), ('OTRO', 'Otro')], default='OTRO', max_length=100),
        ),
    ]
