# Generated by Django 5.0.3 on 2025-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_ficha', models.BigIntegerField(blank=True, null=True)),
                ('inventario', models.CharField(blank=True, max_length=255, null=True)),
                ('n_de_inventario_anterior', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True)),
                ('dimensiones', models.TextField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('alto', models.FloatField(blank=True, null=True)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('profundidad', models.FloatField(blank=True, null=True)),
                ('seguimiento', models.BooleanField(default=False)),
                ('fk_responsable_carga', models.IntegerField(blank=True, null=True)),
                ('fk_estado', models.IntegerField(blank=True, null=True)),
                ('fk_serie', models.IntegerField(blank=True, null=True)),
                ('fk_multimedia_principal', models.IntegerField(blank=True, null=True)),
                ('materiales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
