# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('catalogo_multimedia', '0001_initial'),
        ('estado_obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_ficha', models.BigIntegerField(blank=True, null=True)),
                ('inventario', models.CharField(blank=True, max_length=255, null=True)),
                ('n_de_inventario_anterior', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True)),
                ('estado_conservacion', models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, null=True, verbose_name='Estado de conservación física')),
                ('tipo_ejemplar', models.CharField(blank=True, choices=[('original', 'Original'), ('copia', 'Copia'), ('serie_1', 'Serie 1'), ('serie_2', 'Serie 2'), ('serie_3', 'Serie 3'), ('serie_4', 'Serie 4'), ('serie_5', 'Serie 5'), ('serie_6', 'Serie 6')], max_length=20, null=True)),
                ('edicion', models.CharField(blank=True, help_text='Ej: 3/50, edición limitada, prueba de artista', max_length=255, null=True)),
                ('series_legacy', models.TextField(blank=True, null=True)),
                ('dimensiones', models.TextField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('alto', models.FloatField(blank=True, null=True)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('profundidad', models.FloatField(blank=True, null=True)),
                ('seguimiento', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fichas/')),
                ('autores', models.ManyToManyField(blank=True, related_name='fichas', through='autor.FichaAutor', to='autor.autor')),
                ('fk_estado_funcional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='estado_obra.estadoobra')),
                ('fk_multimedia_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_multimedia.catalogomultimedia')),
            ],
            options={
                'verbose_name': 'Ficha técnica',
                'verbose_name_plural': 'Fichas técnicas',
            },
        ),
    ]
