# Generated by Django 5.0.3 on 2025-11-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_multimedia', '0001_initial'),
        ('ficha_tecnica', '0001_initial'),
        ('material', '0001_initial'),
        ('serie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='fk_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='fk_multimedia_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_multimedia.catalogomultimedia'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='fk_responsable_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='fk_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serie.serie'),
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='materiales',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='materiales',
            field=models.ManyToManyField(related_name='fichas', through='material.FichaTecnicaMaterial', to='material.material'),
        ),
    ]
