# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
        ('material', '0001_initial'),
        ('taller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='fk_responsable_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='fk_taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.taller'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='materiales',
            field=models.ManyToManyField(related_name='fichas', through='material.FichaTecnicaMaterial', to='material.material'),
        ),
    ]
