# Generated by Django 5.0.3 on 2025-12-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='materiales',
            field=models.ManyToManyField(related_name='fichas', through='material.FichaTecnicaMaterial', to='material.material'),
        ),
    ]
