# Generated by Django 5.0.3 on 2025-12-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0002_initial'),
        ('procedencia', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='fk_procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='procedencia.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='inventario',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de inventario'),
        ),
    ]
