# Generated by Django 5.0.3 on 2025-11-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_obra', '0001_initial'),
        ('ficha_tecnica', '0002_alter_fichatecnica_fk_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='fk_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='estado_obra.estadoobra'),
        ),
    ]
