# Generated by Django 5.0.3 on 2025-12-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0003_fichatecnica_fk_procedencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='categoria_objeto',
            field=models.CharField(blank=True, choices=[('PINTURA', 'Pintura'), ('ESCULTURA', 'Escultura'), ('GRABADO', 'Grabado'), ('DIBUJO', 'Dibujo'), ('FOTOGRAFIA', 'Fotografía'), ('CERAMICA', 'Cerámica'), ('TEXTIL', 'Textil'), ('MOBILIARIO', 'Mobiliario'), ('DOCUMENTO', 'Documento'), ('NUMISMATICA', 'Numismática'), ('ARQUEOLOGIA', 'Arqueología'), ('ETNOGRAFIA', 'Etnografía'), ('CIENCIAS_NATURALES', 'Ciencias naturales'), ('INSTRUMENTO', 'Instrumento'), ('INDUMENTARIA', 'Indumentaria'), ('OTRO', 'Otro')], help_text='Dublin Core: dc.type', max_length=50, null=True, verbose_name='Categoría del objeto'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='condiciones_especiales',
            field=models.TextField(blank=True, help_text='Requisitos adicionales de manejo o almacenamiento', null=True, verbose_name='Condiciones especiales de conservación'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='datacion',
            field=models.CharField(blank=True, help_text='Dublin Core: dc.date. Ej: ca. 1850, 1920-1930', max_length=100, null=True, verbose_name='Datación'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='derechos_reproduccion',
            field=models.TextField(blank=True, help_text='Restricciones para fotografía, publicación, etc.', null=True, verbose_name='Derechos de reproducción'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='humedad_requerida_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Humedad relativa máxima (%)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='humedad_requerida_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Humedad relativa mínima (%)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='nivel_confidencialidad',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('RESTRINGIDO', 'Restringido'), ('CONFIDENCIAL', 'Confidencial')], default='PUBLICO', max_length=20, verbose_name='Nivel de confidencialidad'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='nivel_iluminacion',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja (< 50 lux)'), ('MEDIA', 'Media (50-150 lux)'), ('ALTA', 'Alta (150-300 lux)'), ('SIN_RESTRICCION', 'Sin restricción')], max_length=20, null=True, verbose_name='Nivel de iluminación permitido'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='origen_geografico',
            field=models.CharField(blank=True, help_text='Dublin Core: dc.coverage. País/región de creación', max_length=150, null=True, verbose_name='Origen geográfico'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Separadas por coma. Facilita búsquedas', null=True, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='periodo_historico',
            field=models.CharField(blank=True, help_text='Ej: Colonial, Siglo XIX, Art Nouveau', max_length=100, null=True, verbose_name='Período histórico'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='propietario_legal',
            field=models.CharField(blank=True, help_text='Dublin Core: dc.rights', max_length=255, null=True, verbose_name='Propietario legal'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='requiere_vitrina',
            field=models.BooleanField(default=False, verbose_name='Requiere exhibición en vitrina'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tematica',
            field=models.CharField(blank=True, help_text='Dublin Core: dc.subject. Tema principal de la obra', max_length=255, null=True, verbose_name='Temática'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='temperatura_requerida_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura máxima (°C)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='temperatura_requerida_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura mínima (°C)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('PROPIEDAD_MUSEO', 'Propiedad del museo'), ('COMODATO', 'Comodato'), ('DEPOSITO', 'Depósito'), ('PRESTAMO_LARGO', 'Préstamo a largo plazo'), ('EN_TRAMITE', 'En trámite'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='Tipo de propiedad'),
        ),
    ]
