# Generated by Django 5.0.3 on 2025-12-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0003_alter_fichatecnica_fk_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/'),
        ),
    ]
