# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenedor_ubicacion', '0001_initial'),
        ('estado_obra', '0001_initial'),
        ('ficha_tecnica', '0001_initial'),
        ('ubicacion_lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHistorialMov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_contenedor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_destino', to='contenedor_ubicacion.contenedorubicacion')),
                ('fk_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos', to='estado_obra.estadoobra')),
                ('fk_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='ficha_tecnica.fichatecnica')),
                ('fk_lugar_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_destino', to='ubicacion_lugar.ubicacionlugar')),
            ],
        ),
    ]
