# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg_historial_mov', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reghistorialmov',
            name='fk_responsable_mov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
