# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_historial_mov', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reghistorialmov',
            name='motivo',
            field=models.CharField(choices=[('EXPOSICION', 'Exposición'), ('RESTAURACION', 'Restauración'), ('PRESTAMO', 'Préstamo'), ('ALMACENAMIENTO', 'Almacenamiento'), ('INVESTIGACION', 'Investigación'), ('FOTOGRAFIA', 'Fotografía/Documentación'), ('MANTENIMIENTO', 'Mantenimiento'), ('REUBICACION', 'Reubicación'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro')], default='OTRO', max_length=50, verbose_name='Motivo del movimiento'),
        ),
    ]
