# Generated by Django 5.0.3 on 2025-12-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor_ubicacion', '0001_initial'),
        ('reg_historial_mov', '0003_alter_reghistorialmov_motivo'),
        ('ubicacion_lugar', '0003_add_cuarentena_tipo_lugar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reghistorialmov',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En tránsito'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='COMPLETADO', max_length=20, verbose_name='Estado del movimiento'),
        ),
        migrations.AddField(
            model_name='reghistorialmov',
            name='fk_contenedor_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_origen', to='contenedor_ubicacion.contenedorubicacion', verbose_name='Contenedor de origen'),
        ),
        migrations.AddField(
            model_name='reghistorialmov',
            name='fk_lugar_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_origen', to='ubicacion_lugar.ubicacionlugar', verbose_name='Lugar de origen'),
        ),
        migrations.AddField(
            model_name='reghistorialmov',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='reghistorialmov',
            name='fk_contenedor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_destino', to='contenedor_ubicacion.contenedorubicacion', verbose_name='Contenedor de destino'),
        ),
        migrations.AlterField(
            model_name='reghistorialmov',
            name='fk_lugar_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_destino', to='ubicacion_lugar.ubicacionlugar', verbose_name='Lugar de destino'),
        ),
        migrations.AlterField(
            model_name='reghistorialmov',
            name='fk_responsable_mov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del movimiento'),
        ),
        migrations.AlterField(
            model_name='reghistorialmov',
            name='motivo',
            field=models.CharField(choices=[('EXPOSICION', 'Exposición'), ('RESTAURACION', 'Restauración'), ('PRESTAMO', 'Préstamo'), ('ALMACENAMIENTO', 'Almacenamiento'), ('INVESTIGACION', 'Investigación'), ('FOTOGRAFIA', 'Fotografía/Documentación'), ('MANTENIMIENTO', 'Mantenimiento'), ('REUBICACION', 'Reubicación'), ('CUARENTENA', 'Cuarentena'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro')], default='OTRO', max_length=50, verbose_name='Motivo del movimiento'),
        ),
    ]
