# Generated by Django 5.0.3 on 2025-12-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo Multimedia',
                'verbose_name_plural': 'Catálogos Multimedia',
                'ordering': ['ficha', 'tipo'],
            },
        ),
    ]
