# Generated by Django 5.0.3 on 2025-11-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_multimedia', to='ficha_tecnica.fichatecnica')),
            ],
            options={
                'verbose_name': 'Catálogo Multimedia',
                'verbose_name_plural': 'Catálogos Multimedia',
                'ordering': ['ficha', 'tipo'],
            },
        ),
    ]
