# Generated by Django 5.0.3 on 2025-12-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_multimedia', '0001_initial'),
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomultimedia',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_multimedia', to='ficha_tecnica.fichatecnica'),
        ),
    ]
