# Generated by Django 5.0.3 on 2025-12-30 17:02

import apps.catalogo_multimedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_multimedia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogomultimedia',
            name='url_archivo',
        ),
        migrations.AddField(
            model_name='catalogomultimedia',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.catalogo_multimedia.models.get_upload_path, verbose_name='Archivo multimedia'),
        ),
    ]
