# Generated by Django 5.0.3 on 2025-11-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='FichaAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('fk_autor', models.ForeignKey(db_column='fk_autor_id', on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
                ('fk_ficha', models.ForeignKey(db_column='fk_ficha_id', on_delete=django.db.models.deletion.CASCADE, to='ficha_tecnica.fichatecnica')),
            ],
            options={
                'verbose_name': 'Autor de ficha técnica',
                'verbose_name_plural': 'Autores de fichas técnicas',
                'db_table': 'ficha_autor',
                'unique_together': {('fk_ficha', 'fk_autor')},
            },
        ),
    ]
