# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaautor',
            name='fk_ficha',
            field=models.ForeignKey(db_column='fk_ficha_id', on_delete=django.db.models.deletion.CASCADE, to='ficha_tecnica.fichatecnica'),
        ),
        migrations.AlterUniqueTogether(
            name='fichaautor',
            unique_together={('fk_ficha', 'fk_autor')},
        ),
    ]
