# Generated by Django 5.0.3 on 2025-12-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, help_text='(Opcional) Ej: técnica específica del material', max_length=255, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_relacion', to='ficha_tecnica.fichatecnica')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_relacion', to='material.material')),
            ],
            options={
                'verbose_name': 'Relación Ficha–Material',
                'verbose_name_plural': 'Relaciones Ficha–Material',
                'unique_together': {('ficha', 'material')},
            },
        ),
    ]
