# Generated by Django 5.0.3 on 2025-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la plaga')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción general')),
                ('recomendaciones_tratamiento', models.TextField(blank=True, null=True, verbose_name='Recomendaciones de tratamiento')),
                ('historial_apariciones', models.TextField(blank=True, null=True, verbose_name='Historial de apariciones')),
            ],
            options={
                'verbose_name': 'Tipo de plaga',
                'verbose_name_plural': 'Tipos de plagas',
                'ordering': ['nombre'],
            },
        ),
    ]
