# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='contacto',
        ),
        migrations.AddField(
            model_name='taller',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='taller',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='taller',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
