# Generated by Django 5.0.3 on 2025-12-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_ubicacion_actual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regubicacionactual',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
    ]
