# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_plaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoXilofago',
            fields=[
                ('seguimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField()),
                ('observacion', models.TextField()),
                ('nueva_actividad', models.CharField(blank=True, help_text='Opcional: baja, alta, nula', max_length=50, null=True)),
                ('registro_plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='registro_plaga.registroplaga')),
            ],
            options={
                'verbose_name': 'Seguimiento xilófago',
                'verbose_name_plural': 'Seguimientos xilófagos',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
    ]
