# Generated by Django 5.0.3 on 2025-11-23 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0003_alter_fichatecnica_fk_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('investigacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_investigacion', models.PositiveIntegerField(verbose_name='Número de investigación')),
                ('titulo_investigacion', models.CharField(max_length=255, verbose_name='Título de la investigación')),
                ('detalle_investigacion', models.TextField(verbose_name='Detalle')),
                ('anio_realizacion', models.PositiveIntegerField(verbose_name='Año de realización')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigaciones', to='ficha_tecnica.fichatecnica', verbose_name='Ficha técnica')),
                ('investigador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Investigador')),
            ],
            options={
                'verbose_name': 'Investigación',
                'verbose_name_plural': 'Investigaciones',
                'db_table': 'investigacion',
                'ordering': ['ficha', 'num_investigacion'],
            },
        ),
    ]
