# Generated by Django 5.0.3 on 2025-12-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(help_text='Nombre del donante, vendedor o descripción de la procedencia', max_length=255, verbose_name='Nombre/Descripción')),
                ('tipo_procedencia', models.CharField(choices=[('DONACION', 'Donación'), ('COMPRA', 'Compra'), ('LEGADO', 'Legado'), ('TRANSFERENCIA', 'Transferencia'), ('EXCAVACION', 'Excavación'), ('COMODATO', 'Comodato'), ('DEPOSITO', 'Depósito'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=50, verbose_name='Tipo de procedencia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País de origen')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Región/Provincia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('documentacion', models.TextField(blank=True, help_text='Referencias a documentos legales, actas, etc.', null=True, verbose_name='Documentación de respaldo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
                'ordering': ['nombre'],
            },
        ),
    ]
