# Generated by Django 5.0.3 on 2025-12-25 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion_lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenedorUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contenedor', models.CharField(max_length=100)),
                ('tipo_almacen', models.CharField(choices=[('ABIERTO', 'Lugar Abierto'), ('CERRADO', 'Lugar Cerrado')], max_length=20)),
                ('tipo_contenedor', models.CharField(choices=[('CAJON', 'Cajón'), ('CAJA', 'Caja'), ('VITRINA', 'Vitrina'), ('RACK', 'Rack'), ('ESTANTE', 'Estante'), ('SOBRE', 'Sobre'), ('CARPETA', 'Carpeta')], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('fk_lugar_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion_lugar.ubicacionlugar', verbose_name='Lugar general')),
                ('fk_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontenedores', to='contenedor_ubicacion.contenedorubicacion', verbose_name='Contenedor padre')),
            ],
            options={
                'verbose_name': 'Contenedor de Ubicación',
                'verbose_name_plural': 'Contenedores de Ubicación',
            },
        ),
    ]
