# Generated by Django 5.0.3 on 2025-12-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor_ubicacion', '0001_initial'),
        ('ubicacion_lugar', '0003_add_cuarentena_tipo_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedorubicacion',
            name='tipo_almacen',
        ),
        migrations.AddField(
            model_name='contenedorubicacion',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de obras que puede contener. Dejar vacío si no aplica.', null=True, verbose_name='Capacidad máxima (obras)'),
        ),
        migrations.AddField(
            model_name='contenedorubicacion',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARCIAL', 'Parcialmente ocupado'), ('LLENO', 'Lleno'), ('EN_REPARACION', 'En reparación'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado del contenedor'),
        ),
        migrations.AddField(
            model_name='contenedorubicacion',
            name='modo_almacenamiento',
            field=models.CharField(choices=[('DIRECTO', 'Directo (sin contenedor)'), ('EN_CONTENEDOR', 'Dentro de contenedor')], default='EN_CONTENEDOR', max_length=20, verbose_name='Modo de almacenamiento'),
        ),
        migrations.AlterField(
            model_name='contenedorubicacion',
            name='tipo_contenedor',
            field=models.CharField(choices=[('CAJON', 'Cajón'), ('CAJA', 'Caja'), ('VITRINA', 'Vitrina'), ('RACK', 'Rack'), ('ESTANTE', 'Estante'), ('SOBRE', 'Sobre'), ('CARPETA', 'Carpeta'), ('PLANERO', 'Planero'), ('PESEBRE', 'Pesebre'), ('TUBO', 'Tubo'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='contenedorubicacion',
            constraint=models.UniqueConstraint(fields=('nombre_contenedor', 'fk_lugar_general'), name='unique_contenedor_por_lugar'),
        ),
    ]
