# Generated by Django 5.0.3 on 2025-12-25 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0002_initial'),
        ('tipo_plaga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManejoPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del plan MIT')),
                ('propuesta_detalle', models.TextField(verbose_name='Descripción del plan y tratamiento')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_manejo', to='ficha_tecnica.fichatecnica', verbose_name='Obra afectada')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_manejo_plagas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del plan')),
                ('tipo_plaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_asociados', to='tipo_plaga.tipoplaga', verbose_name='Tipo de plaga')),
            ],
            options={
                'verbose_name': 'Plan de manejo de plagas (MIT)',
                'verbose_name_plural': 'Planes de manejo de plagas (MIT)',
                'ordering': ['ficha', 'tipo_plaga'],
            },
        ),
    ]
