# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManejoPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del plan MIT')),
                ('propuesta_detalle', models.TextField(verbose_name='Descripción del plan y tratamiento')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_manejo', to='ficha_tecnica.fichatecnica', verbose_name='Obra afectada')),
            ],
            options={
                'verbose_name': 'Plan de manejo de plagas (MIT)',
                'verbose_name_plural': 'Planes de manejo de plagas (MIT)',
                'ordering': ['ficha', 'tipo_plaga'],
            },
        ),
    ]
