# Generated by Django 5.0.3 on 2025-12-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejo_plagas', '0001_initial'),
        ('tipo_plaga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manejoplagas',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_manejo_plagas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del plan'),
        ),
        migrations.AddField(
            model_name='manejoplagas',
            name='tipo_plaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_asociados', to='tipo_plaga.tipoplaga', verbose_name='Tipo de plaga'),
        ),
    ]
