# Generated by Django 5.0.3 on 2025-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=150, unique=True, verbose_name='Nombre del lugar')),
                ('tipo_lugar', models.CharField(help_text='Ej: SALA, DEPOSITO, TALLER, ARCHIVO, EXTERNO', max_length=50, verbose_name='Tipo de lugar')),
                ('permite_contenedores', models.BooleanField(default=False, verbose_name='¿Permite contenedores?')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Lugar físico',
                'verbose_name_plural': 'Lugares físicos',
                'ordering': ['nombre_lugar'],
            },
        ),
    ]
