# Generated by Django 5.0.3 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion_lugar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionlugar',
            name='tipo_lugar',
            field=models.CharField(choices=[('SALA', 'Sala de exposición'), ('DEPOSITO', 'Depósito'), ('TALLER', 'Taller de restauración'), ('ARCHIVO', 'Archivo'), ('LABORATORIO', 'Laboratorio'), ('EXTERNO', 'Ubicación externa')], max_length=50, verbose_name='Tipo de lugar'),
        ),
    ]
