# Generated by Django 5.0.3 on 2025-11-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('original', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2)),
                ('anio_impresion', models.DateField(blank=True, null=True)),
                ('taller_reimpresion', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='ficha_tecnica.fichatecnica')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['nombre'],
            },
        ),
    ]
