# Generated by Django 5.0.3 on 2025-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50, unique=True, verbose_name='Condición funcional')),
            ],
            options={
                'verbose_name': 'Estado de Obra',
                'verbose_name_plural': 'Estados de Obra',
            },
        ),
    ]
